services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - .:/go/src/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    hostname: db
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  dbdata: null
